---
- name: Capture events posted from Git server
  hosts: all
  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.dashes_to_underscores:

  rules:
    - name: Debug if the webhook has a payload
      condition: event.payload is defined
      action:
        debug:
        
    - name: Respond to push event
      condition: >
        event.payload.repository.name == "gitea/DO274_Demo"
        and event.meta.headers.X_Gitlab_Event == "Push Hook"
        and event.payload.ref is search("master")
      action:
        run_job_template:
          name: Refresh Fact Cache
          organization: "Home Lab"
